# Basic
title: Sixpence
subtitle: Always look up at the moon
welcome_message: <a href="https://github.com/geksong/geksong.github.io" target="_blank">See the code</a>
description: Do not forget to early loyal
creator: <a href="https://github.com/geksong">@geksong</a>

url: "http://geksong.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://github.com/geksong'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: geksong-github-io
    # duoshuo: 
    
# Social
social:
    github: geksong
    mail: zengzhangsong@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
